apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}
  description: A Domain-Driven Design Golang API
  annotations:
    github.com/project-slug: dlopezby93/${{values.repo_name}}
    backstage.io/techdocs-ref: dir:.
  tags:
    - golang
    - api
    - ddd
  links:
    - url: https://github.com/dlopezby93/${{values.repo_name}}
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner}}
  system: ${{values.system}} 